// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hopfvujotiyjbozvimgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcGZ2dWpvdGl5amJvenZpbWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MDgzMjMsImV4cCI6MjA0OTQ4NDMyM30.hmfY_sjNxmVVRlfRZLqg5faJPyJtumOtZhM7EmCWPoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);